Add meetup#2 session info
omni-jp/omni-jp.github.io pull request #3
Opened 2021-04-11 06:49 UTC by hidetakanishihara

please review it.

2021-04-12 06:00 UTC, t-matz requested changes
Added comments.

2021-04-12 06:00 UTC, t-matz commented on content/ja/meetup/002/_index.md
> +    speaker:Hiroshi Tsuji
need a space following colon.
```suggestion
    speaker: Hiroshi Tsuji
```

2021-04-12 06:00 UTC, t-matz commented on content/ja/meetup/002/_index.md
> +      - "https://github.com/omni-jp/meetup/raw/master/"
You can add documents info after uploading materials. Please check same things below.

```suggestion
#    docs: 
#      - "https://github.com/omni-jp/meetup/raw/master/"
```

2021-04-25 16:17 UTC, hidetakanishihara commented on content/ja/meetup/002/_index.md
> +    speaker:Hiroshi Tsuji
Thanks! I fixed it , so please review it again.

2021-04-25 16:18 UTC, hidetakanishihara commented on content/ja/meetup/002/_index.md
> +      - "https://github.com/omni-jp/meetup/raw/master/"
Thanks! I added documents info, so please review it again.

2021-04-26 00:06 UTC, t-matz approved these changes

2021-04-26 00:08 UTC, merged